### ISSUE TITLE
Show default values in usage

### ISSUE THREAD

**Issue by gmagnu** [ToToTec/CmdOption#19]
It would be nice to show the default values with the usage information.

**Comment by lefou** [comment]
What exactly do you have in mind when you say "default value"?

CmdOption itself has no notion of a default value. It especially does not set a default value in case the user provided no option. All it does is to **not** set values for **not** given options.

**Comment by lefou** [comment]
There are some possible posibilities:

* Provide a textual default value via annottion (`@CmdOption(..., defaultValue="1")
* Provide a default value getter method (`public int defaultLogLevel() { return 1; }`)
* Provide some kind of strategie to find default values, e.g. search for getter methods and fields with same name
* Provide a annotation value, which is evaluated lika a script, so that it is possible to provide the default value directly or else invoke some code to compute it (@CmdOption(..., defaultValue="getLogLevel()"`)
